version: '3'
services:
  web:
      image: nginx
      volumes:
        - ./templates:/etc/nginx/templates
      ports:
        - 80:80
      environment:
        - NGINX_PORT=80
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST='%'
    ports:
      - 3306:3306
    volumes:
      - /data/test-app/db

  docker-demo-app:
    image: docker-test.jar
    restart: on-failure
    depends_on:
      - mysql
      - web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/test-app
    ports:
      - 8085:8085
